language: clojure
lein: lein
script: lein test
branches:
  only:
    - master
jdk:
  - openjdk7
  - oraclejdk8
after_success:
- CLOVERAGE_VERSION=1.0.10-SNAPSHOT lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
